'use strict';
const REPO='Berniocal/vedator', BRANCH='main';
const CACHE_KEY='vedator-question-matcher-cache-v5';
const EMBEDDED_DATA=null;
const PUBLIC_BASE='https://bernio.cz/vedator/';
const RAW_BASE=`https://raw.githubusercontent.com/${REPO}/${BRANCH}/`;
const CDN_BASE=`https://cdn.jsdelivr.net/gh/${REPO}@${BRANCH}/`;
const DEFAULT_FAQ_EPISODES=[340,337,332,326,319,313,300,295,289,284,278,272,270,263,257,248,244,226,218,211,203,190,179,170,158,143,138,133,128,119,112,100,89,82,75,69,60,51,35,26,17];
let faqEpisodes=[...DEFAULT_FAQ_EPISODES];
const FALLBACK_ASSETS=[
'episode-17-summary.js','episode-26-summary.js','episode-35-summary.js','episode-51-summary.js','episode-60-summary.js','episode-69-summary.js','episode-75-summary.js','episode-82-summary.js','episode-89-summary.js','episode-100-summary.js','episode-112-summary.js','episode-119-summary.js','episode-128-summary.js','episode-133-summary.js','episode-138-summary.js','episode-143-summary.js','episode-158-summary.js','episode-170-summary.js','episode-179-summary.js','episode-190-summary.js','episode-203-summary.js','episode-211-summary.js','episode-218-summary.js','episode-226-summary.js','episode-244-summary.js','episode-248-summary.js','episode-257-summary.js','episode-263-summary.js','episode-270-summary.js','episode-272-summary.js','episode-278-summary.js','episode-284-summary.js','episode-289-summary.js','episode-295-summary.js','episode-300-chapters.js','episode-313-summary.js','episode-319-summary.js','episode-326-summary.js','episode-332-summary.js','episode-337-summary.js','episode-340-summary.js',
'question-translations-340-part2.js','question-translations-next9.js','question-translations-next12.js','question-translations-332-part2.js','question-translations-332-end-326.js','question-translations-319.js','question-translations-313-part1.js','question-translations-313-end-300.js','question-translations-295-part1.js','question-translations-295-end-289-part1.js','question-translations-289-end-284-part1.js','question-translations-284-end-278-part1.js','question-translations-278-end-272-part1.js','question-translations-272-end-270-part1.js','question-translations-270-end-263-part1.js','question-translations-263-end-257-part1.js','question-translations-257-end-248-part1.js','question-translations-248-end-244-part1.js','question-translations-244-end-226-part1.js','question-translations-226-end-218-part1.js','question-translations-218-end-211-part1.js','question-translations-211-part2.js','question-translations-211-part3.js','question-translations-211-part4.js','question-translations-211-part5.js','question-translations-211-end-203-part1.js','question-translations-203-end-190-part1.js','question-translations-190-end-179-part1.js','question-translations-179-end-170-part1.js','question-translations-170-end-158-part1.js','question-translations-158-part2.js','question-translations-158-part3.js','question-translations-158-part4.js','question-translations-158-part5.js','question-translations-158-part6.js','question-translations-100-part1.js','question-translations-100-part2.js','question-translations-100-part3.js','question-translations-100-part4.js','question-translations-100-part5.js','question-translations-17-end.js'
];
const STOP=new Set(`a aby aj ale anebo ani ano asi až bez bude budou bol bola boli bolo byť byl byla byli bylo by bych bychom byste co což či do ho i jak jako je jej jeho jejich jen jenom ji jí jich jim jimi jinak již k kam kde kdy kdo která které který ku má mají mezi mi mít mne mnou může na nad nám námi ne nebo nech není než nic o od on ona oni ono pak po pod podle pokud pro proč proto při před přes se si sice som sú svoji své svůj ta tak také tam ten tento té tím to toto tu tú ty u už v vám vámi ve velmi vy z za ze že
ako áno až bez bude budú bol bola boli bolo byť by som sme ste čo či do ho i ich im inak je jej jeho len medzi ma má majú mi môcť môže na nad nám nami ne nie alebo než nič o od on ona oni ono po pod podľa pokiaľ pre prečo preto pri pred cez sa si sme som svoj svoje svojí tá tak také tam ten tento tej tým to toto tu tú tie u už v vám vami vo vy z za zo že`.split(/\s+/));
const SUFFIXES=`ovymi evymi ovych evych oveho eveho ovemu evemu ovami evami ovou evou ami emi imi omi ach ech ich och ichu ovia ovie ovia iach ia miami atami enami ovy eva ova ove ovi ovu eho emu ymi imi ami omu ich ych ach ech och ou em am ym im om um ov ev skymi ckymi skeho ckeho skemu ckemu skych ckych nosti nostiach anie enie enia eniu ením enim ování ovani ovaní ujeme ujete ujem ujeju ujuci ující ajú aju ali ala alo aty ate eti ity oti eni ena eno ily ila ilo ete ite ate ych ých ách ích ého iho ými ími ámi émi ou u a e i y o ia ie iu í á é ý ť`.split(/\s+/).sort((a,b)=>b.length-a.length);
const EQUIV=[
['cerna dira','cierna diera','black hole'],['cerne diry','cierne diery'],['vesmir','kozmos','kosmos'],['hvezda','hviezda'],['hvezdy','hviezdy'],['slunce','slnko'],['mesic','mesiac'],['zeme','zem'],['casoprostor','casopriestor'],['umela inteligence','umela inteligencia','ai'],['spolecnost','spolocnost'],['socialni site','socialne siete'],['penize','peniaze'],['mozek','mozog'],['bunka','buṅka'],['rychlost','rychlost'],['svetlo','svetlo'],['voda','voda'],['kyslik','kyslik'],['dusik','dusik'],['uhlik','uhlik'],['jaderna','jadrova'],['jaderny','jadrovy'],['castice','castica'],['castice','castice'],['zarení','ziarenie'],['zareni','ziarenie'],['vlnova delka','vlnova dlzka'],['pravdepodobnost','pravdepodobnost'],['pocitac','pocitac'],['pamet','pamat'],['planetarni','planetarny'],['slunecni soustava','slnecna sustava'],['mlecna draha','mliecna cesta'],['temna hmota','tmava hmota'],['temna energie','tmava energia'],['velky tresk','velky tresk'],['gravitacni vlna','gravitacna vlna'],['elektricky proud','elektricky prud'],['napeti','napatie'],['magneticke pole','magneticke pole'],['sklenikovy efekt','sklenikovy efekt'],['klimaticka zmena','klimaticka zmena'],['zivotni prostredi','zivotne prostredie'],['lidske telo','ludske telo'],['vedomi','vedomie'],['spánek','spanok'],['spanek','spanok'],['nemoc','choroba'],['lecba','liecba'],['lecit','liecit'],['potravina','potravina'],['jídlo','jedlo'],['jidlo','jedlo'],['letadlo','lietadlo'],['vesmirna lod','kozmicka lod'],['raketa','raketa'],['druzice','satelit'],['satelit','druzica'],['pocasi','pocasie'],['mrak','oblak'],['ledovec','ladovec'],['oceán','ocean'],['rovnik','rovnik'],['cas','cas'],['teplota','teplota'],['hmotnost','hmotnost'],['hustota','hustota'],['sila','sila'],['energie','energia'],['elektrina','elektrina'],['baterie','bateria'],['otazka','otazka'],['odpoved','odpoved']
];
let questions=[], df=new Map(), translations=new Map(), loadedAssets=[], corpusSize=1;
const $=s=>document.querySelector(s);
function norm(value){return String(value??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
function esc(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function stem(word){let w=norm(word);if(w.length<5)return w;for(const s of SUFFIXES){if(s&&w.endsWith(s)&&w.length-s.length>=4){w=w.slice(0,-s.length);break}}return w}
function words(text){return norm(text).split(/\s+/).filter(w=>w.length>1&&!STOP.has(w))}
const equivIndex=(()=>{const m=new Map();for(const group of EQUIV){const vals=group.map(norm);for(const v of vals){if(!m.has(v))m.set(v,new Set());for(const x of vals)m.get(v).add(x)}}return m})();
function expandPhrases(text,set){const n=` ${norm(text)} `;for(const [key,vals] of equivIndex){if(n.includes(` ${key} `))for(const v of vals){set.add(v);for(const w of v.split(' '))set.add(stem(w))}}}
function termSet(...texts){const set=new Set();for(const text of texts){for(const w of words(text)){set.add(w);set.add(stem(w));const vals=equivIndex.get(w);if(vals)for(const v of vals){set.add(v);for(const x of v.split(' '))set.add(stem(x))}}expandPhrases(text,set)}return new Set([...set].filter(Boolean))}
function ngrams(text,n=3){const s=norm(text).replace(/\s+/g,' '),out=new Set();if(s.length<n){if(s)out.add(s);return out}for(let i=0;i<=s.length-n;i++)out.add(s.slice(i,i+n));return out}
function decodeJsString(token){if(!token)return'';const q=token[0],body=token.slice(1,-1);let out='';for(let i=0;i<body.length;i++){let c=body[i];if(c!=='\\'){out+=c;continue}c=body[++i];if(c===undefined)break;if(c==='n')out+='\n';else if(c==='r')out+='\r';else if(c==='t')out+='\t';else if(c==='b')out+='\b';else if(c==='f')out+='\f';else if(c==='v')out+='\v';else if(c==='u'){const h=body.slice(i+1,i+5);if(/^[0-9a-f]{4}$/i.test(h)){out+=String.fromCharCode(parseInt(h,16));i+=4}else out+='u'}else if(c==='x'){const h=body.slice(i+1,i+3);if(/^[0-9a-f]{2}$/i.test(h)){out+=String.fromCharCode(parseInt(h,16));i+=2}else out+='x'}else out+=c}return out}
const STR=`(?:'(?:\\\\.|[^'\\\\])*'|"(?:\\\\.|[^"\\\\])*")`;
function fetchText(path){const urls=[RAW_BASE+path,CDN_BASE+path];return (async()=>{let last;for(const url of urls){try{const r=await fetch(url+'?v='+Date.now(),{cache:'no-store'});if(r.ok)return await r.text();last=new Error(`${r.status} ${url}`)}catch(e){last=e}}throw last||new Error('Soubor se nepodařilo načíst')})()}
function extractFaqEpisodes(source){const match=String(source||'').match(/\bFAQ\s*=\s*\[([^\]]+)\]/);if(!match)return[];return[...new Set((match[1].match(/\d+/g)||[]).map(Number).filter(Number.isFinite))];}
function extractAssets(sw){const at=sw.indexOf('const ASSETS=');if(at<0)return[];const open=sw.indexOf('[',at);let depth=0,end=-1,quote='',escp=false;for(let i=open;i<sw.length;i++){const c=sw[i];if(quote){if(escp)escp=false;else if(c==='\\')escp=true;else if(c===quote)quote='';continue}if(c==='"'||c==="'"){quote=c;continue}if(c==='[')depth++;else if(c===']'&&--depth===0){end=i+1;break}}if(end<0)return[];const block=sw.slice(open,end),re=new RegExp(STR,'g');return [...block.matchAll(re)].map(m=>decodeJsString(m[0]))}
function parsePairs(src){const pairRe=new RegExp(`\\[\\s*(${STR})\\s*,\\s*(${STR})\\s*\\]`,'g');for(const m of src.matchAll(pairRe)){const a=decodeJsString(m[1]).trim(),b=decodeJsString(m[2]).trim();if(!a||!b)continue;const pair={a,b};translations.set(norm(a),pair);translations.set(norm(b),pair)}}
function fmtSeconds(value){const n=Math.max(0,Math.floor(Number(value)||0)),h=Math.floor(n/3600),m=Math.floor(n%3600/60),r=n%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(r).padStart(2,'0')}`:`${m}:${String(r).padStart(2,'0')}`}
