function parseGeneric(path,src,forcedEpisode=null){
  const episode=forcedEpisode||Number(path.match(/episode-(\d+)/)?.[1]||0),out=[];
  // Aplikace u běžných časů odečítá pětisekundový náběh. Soubory, které už mají
  // data-vedator-preroll, obsahují čas připravený pro přímý odkaz a znovu se neposouvají.
  const prerollSeconds=/data-vedator-preroll/i.test(src)?0:5;
  const add=(time,title,offset=0)=>{title=String(title||'').replace(/^\s*\d+[.)]\s*/,'').trim();if(episode&&title.length>=3){const rawTime=String(time||'');out.push({episode,time:rawTime,link_seconds:Math.max(0,toSec(rawTime)-prerollSeconds),title,source:path,offset})}};
  const objectTime=new RegExp(`\\{[\\s\\S]{0,600}?\\btime\\s*:\\s*(${STR})[\\s\\S]{0,600}?\\btitle\\s*:\\s*(${STR})`,'g');
  for(const m of src.matchAll(objectTime))add(decodeJsString(m[1]).trim(),decodeJsString(m[2]),m.index||0);
  const objectSeconds=new RegExp(`\\{[\\s\\S]{0,400}?\\bseconds\\s*:\\s*(\\d+(?:\\.\\d+)?)[\\s\\S]{0,400}?\\btitle\\s*:\\s*(${STR})`,'g');
  for(const m of src.matchAll(objectSeconds))add(fmtSeconds(m[1]),decodeJsString(m[2]),m.index||0);
  const tuple=new RegExp(`\\[\\s*(${STR})\\s*,\\s*(${STR})\\s*,\\s*\\[`,'g');
  for(const m of src.matchAll(tuple)){const t=decodeJsString(m[1]).trim();if(/^\d{1,2}:\d{2}(?::\d{2})?$/.test(t))add(t,decodeJsString(m[2]),m.index||0)}
  return dedupe(out);
}
function matchingBracket(src,open){let depth=0,quote='',escaped=false,line=false,block=false;for(let i=open;i<src.length;i++){const c=src[i],n=src[i+1];if(line){if(c==='\n')line=false;continue}if(block){if(c==='*'&&n==='/'){block=false;i++}continue}if(quote){if(escaped)escaped=false;else if(c==='\\')escaped=true;else if(c===quote)quote='';continue}if(c==='/'&&n==='/'){line=true;i++;continue}if(c==='/'&&n==='*'){block=true;i++;continue}if(c==='"'||c==="'"||c==='`'){quote=c;continue}if(c==='[')depth++;else if(c===']'&&--depth===0)return i}return-1}
function parseChapterGroups(path,src){const out=[];const start=src.search(/\bCHAPTERS\s*=\s*\{/);if(start<0)return out;const keyRe=/(\d{1,4})\s*:\s*\[/g;keyRe.lastIndex=start;let m;while((m=keyRe.exec(src))){const episode=Number(m[1]);if(!faqEpisodes.includes(episode))continue;const open=src.indexOf('[',m.index),end=matchingBracket(src,open);if(end<0)continue;const block=src.slice(open,end+1);out.push(...parseGeneric(path,block,episode));keyRe.lastIndex=end+1}return dedupe(out)}
function parseInline300(src){return parseGeneric('index.html#SUMMARIES-300',src,300)}
function findTranslation(title){const exact=translations.get(norm(title));if(exact)return exact;let best=null,score=0;const a=ngrams(title);for(const pair of new Set(translations.values())){for(const candidate of [pair.a,pair.b]){const b=ngrams(candidate),s=dice(a,b);if(s>score){score=s;best=pair}}}return score>=.91?best:null}
function dice(a,b){if(!a.size&&!b.size)return 1;let n=0;for(const x of a)if(b.has(x))n++;return 2*n/(a.size+b.size||1)}
function isLikelyCzech(text){const n=' '+norm(text)+' ';const cz=[' proc ',' jaky ',' kter',' muze ',' svet',' zeme ',' hvez',' mesic ',' slunce ',' diky ',' zadny ',' budou ',' kdyz ',' nej'];const sk=[' preco ',' aky ',' ktory',' moze ',' svet',' zem ',' hviez',' mesiac ',' slnko ',' vdaka ',' ziadny ',' budu ',' ked ',' naj'];let c=0,s=0;for(const x of cz)if(n.includes(x))c++;for(const x of sk)if(n.includes(x))s++;return c>=s}
function chooseLanguages(title){const p=findTranslation(title);if(p)return{cs:p.a,sk:p.b};return isLikelyCzech(title)?{cs:title,sk:''}:{cs:'',sk:title}}
function dedupe(items){const seen=new Map();for(const q of items){const key=`${q.episode}|${norm(q.title)}`;if(!seen.has(key))seen.set(key,q)}return [...seen.values()]}
function buildIndex(items){corpusSize=Math.max(1,items.length);items.sort((a,b)=>b.episode-a.episode||(toSec(a.time)-toSec(b.time))||String(a.title||a.question_cs||a.question_sk||'').localeCompare(String(b.title||b.question_cs||b.question_sk||''),'cs'));const perEp=new Map();for(const item of items){item.title=String(item.title||item.question_cs||item.question_sk||'');const lang=(item.question_cs||item.question_sk)?{cs:item.question_cs||item.title,sk:item.question_sk||''}:chooseLanguages(item.title);const cs=lang.cs||item.title,sk=lang.sk||'';const terms=termSet(cs,sk,item.title);const chargrams=ngrams(`${cs} ${sk||item.title}`);const calculated=(perEp.get(item.episode)||0)+1;perEp.set(item.episode,calculated);const order=Number(item.order)||calculated;if(!Number.isFinite(Number(item.link_seconds)))item.link_seconds=Math.max(0,toSec(item.time)-5);Object.assign(item,{order,question_cs:cs,question_sk:sk,terms,chargrams})}df=new Map();for(const q of items)for(const t of q.terms)df.set(t,(df.get(t)||0)+1);for(let i=0;i<items.length;i++){const q=items[i];q.id=i+1;q.keyword_list=[...q.terms].sort((a,b)=>keywordWeight(b)-keywordWeight(a)||a.localeCompare(b,'cs')).slice(0,24);q.normalized=norm(`${q.question_cs} ${q.question_sk}`);q.search_terms=[...q.terms].sort();q.vector=vector(q.terms)}return items}
