'use strict';

/*
  Mapy významově stejných formulací pro vyhledávání Vedátoru.
  Vychází z opakujících se formulací v otázkách i neotázkách:
  lidová otázka -> odborný pojem v názvu nebo odpovědi.
*/
window.VEDATOR_SEARCH_MAPS = {
  equivalents: [
    // --- Veličiny a číselné dotazy ---
    ['hmotnost', ['hmotnost','hmotnosti','hmotnostní','hmotnostny','hmotnosť','hmotnosti','váha','vaha','váží','vazi','vážit','vazit','váži','vazi','vážia','vazia','kg','kilogram','kilogramy','kilogramů','kilogramu','kilogramov','mass']],
    ['trvani', ['trvání','trvani','trvanie','doba','trvá','trva','trvají','trvaji','trvajú','trvaju','doba trvání','doba trvania','čas trvání','cas trvani','čas trvania','cas trvania','duration']],
    ['vzdalenost', ['vzdálenost','vzdalenost','vzdialenosť','vzdialenost','daleko','vzdálený','vzdaleny','vzdialený','vzdialeny','distance']],
    ['rychlost', ['rychlost','rýchlosť','rychlostí','rychlosti','rýchlosťou','rychle','rýchlo','speed','velocity']],
    ['vek', ['věk','vek','stáří','stari','starý','stary','stará','stara','staré','stare','vek člověka','vek cloveka','age']],
    ['velikost', ['velikost','veľkosť','velkost','velký','velky','velká','velka','velké','velke','rozměr','rozmer','rozměry','rozmery','rozměrech','rozmeroch','size','dimensions']],
    ['delka', ['délka','delka','dĺžka','dlzka','dlouhý','dlouhy','dlouhá','dlouha','dlhý','dlhy','length']],
    ['vyska', ['výška','vyska','výšce','vysce','vysoký','vysoky','vysoká','vysoka','height']],
    ['hloubka', ['hloubka','hĺbka','hlbka','hluboký','hluboky','hlboký','hlboky','depth']],
    ['sirka', ['šířka','sirka','šířce','sirce','široký','siroky','width']],
    ['plocha', ['plocha','rozloha','povrchová plocha','povrchova plocha','area']],
    ['objem', ['objem','objemu','litr','litry','litrů','litru','liter','litrov','volume']],
    ['teplota', ['teplota','teploty','teplotě','teplote','stupně','stupne','stupňů','stupnu','celsius','celsia','temperature']],
    ['pocet', ['počet','pocet','množství','mnozstvi','množstvo','mnozstvo','number','amount']],
    ['frekvence', ['frekvence','frekvencia','četnost','cetnost','často','casto','hertz','hz','frequency']],
    ['cena', ['cena','ceny','náklady','naklady','cost','price']],
    ['spotreba', ['spotřeba','spotreba','spotřebuje','spotrebuje','spotřebují','spotrebuju','consumption']],
    ['produkce', ['produkce','produkcia','produkovať','produkovat','produkuje','vyprodukuje','vyprodukují','vyprodukuju','production']],

    // --- Typ informace / význam otázky ---
    ['slozeni', ['složení','slozeni','zloženie','zlozenie','součást','soucast','součásti','soucasti','súčasť','sucast','část','cast','části','casti','častí','casti','složka','slozka','skládá','sklada','skladajú','skladaju','tvoří','tvori','obsahuje','komponenta','component','composition']],
    ['material', ['materiál','material','materiálu','materialu','vyrobený','vyrobeny','vyrobená','vyrobena','made of']],
    ['princip', ['princip','principem','mechanismus','mechanizmus','funguje','fungování','fungovani','fungovanie','pracuje','working principle']],
    ['ucel', ['účel','ucel','slouží','slouzi','slúži','sluzi','funkce','funkcia','využití','vyuziti','využitie','vyuzitie','použití','pouziti','purpose']],
    ['definice', ['definice','definícia','definicia','znamená','znamena','význam','vyznam','definition','meaning']],
    ['pricina', ['příčina','pricina','príčina','důvod','duvod','dôvod','zpusobuje','způsobuje','spôsobuje','cause','reason']],
    ['vznik', ['vznik','vzniká','vznika','vznikají','vznikaji','vznikajú','vznikaju','vytvoření','vytvoreni','formování','formovani','formation','origin process']],
    ['poloha', ['poloha','umístění','umisteni','umiestnenie','nachází','nachazi','nachádza','nachadza','location']],
    ['rozdil', ['rozdíl','rozdil','rozdiel','liší','lisi','líši','odlišnost','odlisnost','porovnání','porovnani','srovnání','srovnani','difference','comparison']],
    ['moznost', ['možnost','moznost','možné','mozne','lze','dokáže','dokaze','dokážu','dokazu','possible','possibility']],
    ['dusledek', ['důsledek','dusledek','dôsledok','následek','nasledek','následok','nasledok','consequence','result']],
    ['mereni', ['měření','mereni','meranie','změřit','zmerit','merať','merat','measurement']],
    ['vypocet', ['výpočet','vypocet','výpočet','spočítat','spocitat','vypočítat','vypocitat','počítať','pocitat','calculation']],
    ['nazev', ['název','nazev','názov','nazov','jmenuje','volá','vola','pojmenování','pojmenovani','name']],
    ['puvod', ['původ','puvod','pôvod','pochází','pochazi','pochádza','pochadza','origin']],
    ['vliv', ['vliv','vplyv','ovlivňuje','ovlivnuje','ovplyvňuje','ovplyvnuje','působí','pusobi','effect','influence']],
    ['metoda', ['metoda','způsob','zpusob','spôsob','sposob','postup','method','procedure']],

    // --- Odborné a jazykové ekvivalence ---
    ['cerna dira', ['černá díra','cerna dira','černé díry','cerne diry','černých děr','cernych der','čierna diera','cierna diera','čierne diery','cierne diery','black hole','black holes']],
    ['vesmir', ['vesmír','vesmir','kosmos','kozmos','universe','cosmos']],
    ['hvezda', ['hvězda','hvezda','hvězdy','hvezdy','hviezda','hviezdy','star','stars']],
    ['slunce', ['slunce','sluneční','slunecni','slnko','slnečný','slnecny','sun','solar']],
    ['mesic', ['měsíc','mesic','měsíční','mesicni','mesiac','mesačný','mesacny','moon','lunar']],
    ['zeme', ['země','zeme','zemský','zemsky','zem','earth','terrestrial']],
    ['casoprostor', ['časoprostor','casoprostor','časopriestor','casopriestor','spacetime']],
    ['umela inteligence', ['umělá inteligence','umela inteligence','umelá inteligencia','umela inteligencia','AI','artificial intelligence']],
    ['svetlo', ['světlo','svetlo','světelný','svetelny','svetelný','light']],
    ['foton', ['foton','fotony','fotonový','fotonovy','fotón','fotóny','photon','photons']],
    ['kvantum', ['kvantum','kvanta','kvantový','kvantovy','kvantová fyzika','kvantova fyzika','quantum']],
    ['gravitace', ['gravitace','gravitační','gravitacni','gravitácia','gravitacia','gravitačný','gravitacny','gravity']],
    ['relativita', ['relativita','relativistický','relativisticky','relativity']],
    ['elektromagneticke zareni', ['elektromagnetické záření','elektromagneticke zareni','elektromagnetické vlnění','elektromagneticke vlneni','elektromagnetické žiarenie','elektromagneticke ziarenie','electromagnetic radiation']],
    ['zareni', ['záření','zareni','žiarenie','ziarenie','radiation']],
    ['optika', ['optika','optický','opticky','optics']],
    ['vlna', ['vlna','vlny','vlnová','vlnova','vlnenie','vlnění','wave','waves']],
    ['energie', ['energie','energia','energy']],
    ['elektron', ['elektron','elektrony','elektrón','elektróny','electron','electrons']],
    ['proton', ['proton','protony','protón','protóny','protons']],
    ['neutron', ['neutron','neutrony','neutrón','neutróny','neutrons']],
    ['kvark', ['kvark','kvarky','quark','quarks']],
    ['atom', ['atom','atomy','atóm','atómy','atoms']],
    ['molekula', ['molekula','molekuly','molekulární','molekularni','molecule','molecules']],
    ['castice', ['částice','castice','častica','castica','particle','particles']],
    ['jadro', ['jádro','jadro','jaderný','jaderny','jadrový','jadrovy','nucleus','nuclear']],
    ['magnet', ['magnet','magnetický','magneticky','magnetic']],
    ['elektrina', ['elektřina','elektrina','elektrický','elektricky','electricity','electric']],
    ['zvuk', ['zvuk','zvukový','zvukovy','sound']],
    ['evoluce', ['evoluce','evoluční','evolucni','evolúcia','evolucia','evolution']],
    ['gen', ['gen','geny','genetický','geneticky','gene','genes','genetics']],
    ['dna', ['DNA','deoxyribonukleová kyselina','deoxyribonukleova kyselina']],
    ['bunka', ['buňka','bunka','buňky','bunky','cell','cells']],
    ['klima', ['klima','klimatický','klimaticky','klimatická změna','klimaticka zmena','climate']],
    ['sklenikovy efekt', ['skleníkový efekt','sklenikovy efekt','skleníkový plyn','sklenikovy plyn','greenhouse effect']],
    ['co2', ['CO2','oxid uhličitý','oxid uhlicity','carbon dioxide']],
    ['pocitac', ['počítač','pocitac','počítače','pocitace','computer','computers']],
    ['algoritmus', ['algoritmus','algoritmy','algorithm','algorithms']],
    ['neuronova sit', ['neuronová síť','neuronova sit','neurónová sieť','neuronova siet','neural network']],
    ['laser', ['laser','lasery','laserový','laserovy']],
    ['horizont udalosti', ['horizont událostí','horizont udalosti','horizont udalostí','event horizon']],
    ['singularita', ['singularita','singularity']],
    ['hawkingovo zareni', ['Hawkingovo záření','hawkingovo zareni','Hawkingovo žiarenie','hawking radiation']],
    ['galaxie', ['galaxie','galaxia','galaxy','galaxies']],
    ['planeta', ['planeta','planety','planetární','planetarni','planetárny','planetarny','planet','planets']],
    ['orbita', ['oběžná dráha','obezna draha','orbita','orbitální dráha','orbitalni draha','obežná dráha','orbit']],
    ['rychlost svetla', ['rychlost světla','rychlost svetla','rýchlosť svetla','speed of light']],
    ['velky tresk', ['velký třesk','velky tresk','veľký tresk','big bang']],
    ['temna hmota', ['temná hmota','temna hmota','tmavá hmota','tmava hmota','dark matter']],
    ['temna energie', ['temná energie','temna energie','tmavá energia','tmava energia','dark energy']],
    ['slunecni soustava', ['sluneční soustava','slunecni soustava','slnečná sústava','slnecna sustava','solar system']],
    ['mlecna draha', ['Mléčná dráha','mlecna draha','Mliečna cesta','mliecna cesta','Milky Way']],
    ['druzice', ['družice','druzice','satelit','satelity','satellite','satellites']],
    ['exoplaneta', ['exoplaneta','exoplanety','extrasolární planeta','extrasolarni planeta','exoplanet']]
  ],

  // Fráze se vyhodnocují především u dotazu. Díky nim se nemíchá např. "jak dlouho" s "jak dlouhý".
  queryPhrases: [
    ['hmotnost', ['kolik váží','kolik vazi','koľko váži','kolko vazi','jakou má hmotnost','jakou ma hmotnost','akú má hmotnosť','aku ma hmotnost','jaká je hmotnost','jaka je hmotnost']],
    ['trvani', ['jak dlouho','ako dlho','za jak dlouho','za ako dlho','jakou dobu','akú dobu','kolik času','kolko casu']],
    ['vzdalenost', ['jak daleko','ako ďaleko','ako daleko','v jaké vzdálenosti','v jake vzdalenosti','v akej vzdialenosti']],
    ['rychlost', ['jak rychle','ako rýchlo','ako rychlo','jakou rychlostí','jakou rychlosti','akou rýchlosťou','akou rychlostou']],
    ['vek', ['jak starý','jak stary','jak stará','jak stara','ako starý','ako stary','ako stará','ako stara','jaký má věk','jaky ma vek','aký má vek','aky ma vek']],
    ['velikost', ['jak velký','jak velky','jak velká','jak velka','jak velké','jak velke','ako veľký','ako velky','ako veľká','ako velka','jaké má rozměry','jake ma rozmery']],
    ['delka', ['jak dlouhý','jak dlouhy','jak dlouhá','jak dlouha','ako dlhý','ako dlhy','ako dlhá','ako dlha','jakou má délku','jakou ma delku','akú má dĺžku','aku ma dlzku']],
    ['vyska', ['jak vysoký','jak vysoky','jak vysoká','jak vysoka','ako vysoký','ako vysoky','ako vysoká','ako vysoka','jakou má výšku','jakou ma vysku']],
    ['hloubka', ['jak hluboký','jak hluboky','jak hluboká','jak hluboka','ako hlboký','ako hlboky','jaká je hloubka','jaka je hloubka']],
    ['sirka', ['jak široký','jak siroky','jak široká','jak siroka','ako široký','ako siroky','jakou má šířku','jakou ma sirku']],
    ['plocha', ['jak velkou plochu','jaká je plocha','jaka je plocha','jaká je rozloha','jaka je rozloha','aká je rozloha','aka je rozloha']],
    ['objem', ['jaký má objem','jaky ma objem','aký má objem','aky ma objem','kolik litrů','kolik litru','koľko litrov','kolko litrov']],
    ['teplota', ['jakou má teplotu','jakou ma teplotu','jaká je teplota','jaka je teplota','akú má teplotu','aku ma teplotu','aká je teplota','aka je teplota','kolik stupňů','kolik stupnu','koľko stupňov','kolko stupnov']],
    ['pocet', ['kolik je','koľko je','kolko je','kolik existuje','koľko existuje','kolko existuje','jaký je počet','jaky je pocet','aký je počet','aky je pocet']],
    ['frekvence', ['jak často','ako často','ako casto','s jakou frekvencí','s jakou frekvenci','s akou frekvenciou']],
    ['cena', ['kolik stojí','kolik stoji','koľko stojí','kolko stoji','jaká je cena','jaka je cena','aká je cena','aka je cena']],
    ['spotreba', ['kolik spotřebuje','kolik spotrebuje','koľko spotrebuje','jaká je spotřeba','jaka je spotreba','aká je spotreba','aka je spotreba']],
    ['produkce', ['kolik vyprodukuje','kolik vyrobí','kolik vyrobi','koľko vyprodukuje','koľko vyrobí','kolko vyrobi']],
    ['slozeni', ['z jakých částí','z jakych casti','z akých častí','z akych casti','z čeho se skládá','z ceho se sklada','z čoho sa skladá','z coho sa sklada','co obsahuje','čo obsahuje','co je součástí','co je soucasti','čo je súčasťou','co tvori','co tvoří']],
    ['material', ['z čeho je','z ceho je','z čoho je','z coho je','z jakého materiálu','z jakeho materialu','z akého materiálu','z akeho materialu','z čeho je vyroben','z ceho je vyroben']],
    ['princip', ['jak funguje','jak fungují','jak funguji','ako funguje','ako fungujú','ako funguju','na jakém principu','na jakem principu','na akom princípe','na akom principe']],
    ['ucel', ['k čemu slouží','k cemu slouzi','na co slouží','na co slouzi','na čo slúži','na co sluzi','k čemu se používá','k cemu se pouziva','na čo sa používa','na co sa pouziva']],
    ['definice', ['co je','co je to','čo je','co znamena','co znamená','čo znamená','co se rozumí','co se rozumi']],
    ['pricina', ['proč','prečo','z jakého důvodu','z jakeho duvodu','z akého dôvodu','z akeho dovodu','co způsobuje','co zpusobuje','čo spôsobuje','co je příčinou','co je pricinou']],
    ['vznik', ['jak vzniká','jak vznika','jak vznikají','jak vznikaji','ako vzniká','ako vznika','ako vznikajú','ako vznikaju','jak se vytvoří','jak se vytvori','ako sa vytvorí']],
    ['poloha', ['kde je','kde se nachází','kde se nachazi','kde sa nachádza','kde sa nachadza','kde leží','kde lezi']],
    ['rozdil', ['jaký je rozdíl','jaky je rozdil','aký je rozdiel','aky je rozdiel','rozdíl mezi','rozdil mezi','rozdiel medzi','v čem se liší','v cem se lisi','v čom sa líši','v com sa lisi']],
    ['moznost', ['je možné','je mozne','je možné aby','dá se','da se','dá sa','da sa','může','môže','moze','lze']],
    ['dusledek', ['co se stane','co se stane když','co se stane kdyz','co by se stalo','čo sa stane','co sa stane','co by sa stalo','jaký bude následek','jaky bude nasledek']],
    ['mereni', ['jak se měří','jak se meri','ako sa meria','jak změřit','jak zmerit','ako zmerať','ako zmerat']],
    ['vypocet', ['jak se počítá','jak se pocita','ako sa počíta','ako sa pocita','jak spočítat','jak spocitat','jak vypočítat','jak vypocitat']],
    ['nazev', ['jak se jmenuje','jak se to jmenuje','ako sa volá','ako sa vola','jaký je název','jaky je nazev','aký je názov','aky je nazov']],
    ['puvod', ['odkud pochází','odkud pochazi','odkiaľ pochádza','odkial pochadza','jaký má původ','jaky ma puvod','aký má pôvod','aky ma povod']],
    ['vliv', ['jak ovlivňuje','jak ovlivnuje','ako ovplyvňuje','ako ovplyvnuje','jaký má vliv','jaky ma vliv','aký má vplyv','aky ma vplyv']],
    ['metoda', ['jak se dá','jak se da','ako sa dá','ako sa da','jak lze','jak můžeme','jak muzeme','ako môžeme','ako mozeme']]
  ],

  // Příbuzné, ale ne totožné pojmy. Používají se až jako slabší fallback.
  semanticEdges: [
    ['foton','svetlo',.78],['foton','elektromagneticke zareni',.68],['foton','kvantum',.64],['foton','zareni',.62],['foton','energie',.50],['foton','vlna',.46],['foton','optika',.54],
    ['svetlo','optika',.78],['svetlo','elektromagneticke zareni',.72],['svetlo','vlna',.68],['svetlo','laser',.63],['svetlo','rychlost svetla',.58],
    ['cerna dira','gravitace',.86],['cerna dira','relativita',.82],['cerna dira','casoprostor',.80],['cerna dira','horizont udalosti',.94],['cerna dira','singularita',.91],['cerna dira','hawkingovo zareni',.82],['cerna dira','galaxie',.50],['cerna dira','hvezda',.56],
    ['gravitace','relativita',.79],['gravitace','casoprostor',.78],['gravitace','orbita',.68],['gravitace','planeta',.58],['gravitace','hvezda',.55],
    ['relativita','casoprostor',.88],['relativita','rychlost svetla',.72],
    ['kvantum','castice',.78],['kvantum','atom',.67],['kvantum','elektron',.68],['kvantum','foton',.64],['kvantum','vlna',.60],
    ['castice','elektron',.80],['castice','proton',.80],['castice','neutron',.80],['castice','kvark',.78],['castice','foton',.62],['castice','jadro',.55],
    ['atom','elektron',.80],['atom','proton',.73],['atom','neutron',.73],['atom','molekula',.72],['atom','jadro',.68],
    ['elektromagneticke zareni','zareni',.92],['elektromagneticke zareni','vlna',.82],['elektromagneticke zareni','svetlo',.72],
    ['vesmir','galaxie',.78],['vesmir','hvezda',.75],['vesmir','planeta',.70],['vesmir','velky tresk',.62],['vesmir','temna hmota',.58],['vesmir','temna energie',.58],
    ['galaxie','hvezda',.72],['planeta','orbita',.72],['planeta','hvezda',.58],['slunecni soustava','planeta',.82],['slunecni soustava','slunce',.84],['mlecna draha','galaxie',.95],['druzice','orbita',.68],['exoplaneta','planeta',.90],
    ['evoluce','gen',.68],['evoluce','dna',.60],['gen','dna',.88],['gen','bunka',.62],['dna','bunka',.66],
    ['klima','sklenikovy efekt',.78],['klima','co2',.70],['klima','teplota',.60],['sklenikovy efekt','co2',.80],
    ['umela inteligence','algoritmus',.80],['umela inteligence','neuronova sit',.78],['umela inteligence','pocitac',.62],['algoritmus','pocitac',.58],
    // blízké veličiny / formulace, které nejsou totožné
    ['velikost','delka',.72],['velikost','vyska',.66],['velikost','sirka',.66],['velikost','plocha',.48],['velikost','objem',.48],
    ['frekvence','trvani',.24],['pricina','vliv',.55],['slozeni','material',.78],['princip','metoda',.42]
  ]
};
